"""Added image column to vehicle and user

Revision ID: 422bbe15f0e8
Revises: 2f4740980dc2
Create Date: 2024-10-16 09:48:29.751223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422bbe15f0e8'
down_revision = '2f4740980dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=50), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
